### ISSUE TITLE
Test app doesn't work.

### ISSUE THREAD

**Issue by haruska** [Terminal-Systems/apollo-cursor-pagination#2]
The project seems a bit stale? For the test app:

I had to upgrade nodemon for yarn to install. Then a `yarn start` yields:
```
Error: Cannot find module 'apollo-cursor-pagination/orm-implementations/knex'
```
I think this has changed to `apollo-cursor-pagination/orm-connectors/knex` in the actual package.

Is there a current example of using the knex connector? using the `paginate` example in the README yields a `knex.default is not a function` TypeError when passing in a knex query.

**Comment by dmerrill6** [comment]
Hello @haruska ,

Thanks for your report. Indeed, the test app had an incorrect import. This was just fixed in PR #3 . 

Can you pull the changes and check if it runs correctly for you now? The knex connector should be used just like the test app or the readme example. The test app is now passing successfully in my machine when running `yarn test`.

Let me know if you run into any issues to better troubleshoot them.

**Comment by haruska** [comment]
Thanks! still fails with default `custom-pagination` ... however, using the `offset-based-pagination` knex connector seems to work fine.

**Comment by dmerrill6** [comment]
I see... Offset based should be fine if you don't worry about stable pagination (unstable pagination means that if you add a new record cursors might change). 

The `knex.default is not a function`  sounds like a babel issue with the ES6 `import` syntax, but the dist version should have that transpiled. 

Will try to replicate the issue. Which version of node are you using?

**Comment by haruska** [comment]
I'm using typescript v3.2.2 and node v8.14

```
$ ts-node -v
ts-node v7.0.1
node v8.14.0
typescript v3.2.2
```

Similar problem on node v11. I'm locked into v8 due to AWS Lambda constraints.

There must be something different on the transpile between `custom` and `offset-based`

**Comment by dmerrill6** [comment]
Thanks for your help on debugging the issue!

We just published a new version (`0.2.0`) that should fix this. Could you please update your package.json to point to the new one to check if it's fixed for you?

**Comment by haruska** [comment]
And thank you for the fix!

I can't seem to import the knex connector anymore with `0.2.0`. My import statement in TypeScript is:
```
import * as paginate from 'apollo-cursor-pagination/orm-connectors/knex/offset-based-pagination'
```
Which works fine in `0.1.0`. Is there a different export to use?


Ideally, it would be cleaned up that you could do something like
```
import { paginate } from 'apollo-cursor-pagination/orm/knex'
```
or similar.

**Comment by dmerrill6** [comment]
Closing for inactivity
